### ISSUE TITLE
Indentation wrong in code blocks.

### ISSUE THREAD

**Issue by shivanshu-semwal** [ryangrose/easy-pandoc-templates#1]
https://github.com/ryangrose/easy-pandoc-templates/blob/6d9c95a3e4656d4408f72e5c6f039540842d3082/html/easy_template.html#L108

This indent in the template cause the code blocks having extra indent. 

![image](https://user-images.githubusercontent.com/53912074/137574756-98dca489-f373-4abe-8e86-e9389b98760b.png)

**Comment by ryangrose** [comment]
Hey @shivanshu-semwal, thanks for flagging. Just removed it: [ix: remove indentation from code blocks ](https://github.com/ryangrose/easy-pandoc-templates/commit/2ec716249516d7429419fbf87304f6a48d77eb88)
