### ISSUE TITLE
remote_install.sh not available?

### ISSUE THREAD

**Issue by k-butz** [ryangrose/easy-pandoc-templates#2]
Hi, I'm trying to install the templates via:
`curl 'https://raw.githubusercontent.com/ryangrose/easy-pandoc-templates/master/remote_install.sh`

I'm receiving a 404 here, is this script still in place? Any hint how to install?

// Edit: Note, seems it's only the script missing, downloading single templates works fine.

**Comment by ryangrose** [comment]
Hey @ButKor, thanks for flagging! And apologies for the delay, I didn't get any notifications. Looks like I forgot to update the filename there. Should be working now: [ fix: correct one-line install ](https://github.com/ryangrose/easy-pandoc-templates/commit/c080c345a5b381263984c6e6443df9bcf11729fd)
